version: '3.2'
services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
    - 8080:80
    - 2003-2004:2003-2004
    - 2023-2024:2023-2024
    - 8125:8125/udp
    - 8126:8126
    volumes:
    - ./data/graphite-storage:/opt/graphite/storage
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
#    user: "104"
    volumes: 
    - ./data/grafana-storage:/var/lib/grafana:rw

  auto-telemetry-collector:
    image: inosion/auto-telemetry
    container_name: auto-telemetry-collector
    volumes:
      # - ./bluetooth-rfcomm.conf:/etc/bluetooth/rfcomm.conf:ro
      - ./auto-telemetry-collector.py:/usr/local/bin/auto-telemetry-collector.py:ro
    ports:
     - 8000:8000
    volumes:
      - ./:/host:ro
      - /dev:/dev:rw
      - /var:/var:rw
      - /sys:/sys:rw
    privileged: true
    working_dir: /host
    environment:
      - ATC_CONFIG=/etc/auto-telemetry-collector/default-auto-telemetry-config.yaml    
    command: ["monitor", "--device", "/dev/ttyUSB0" , "--config", "${ATC_CONFIG}"]
    depends_on:
      - grafana
