version: '3.2'
services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    ports:
    - 8086:8086
    - 8089:8089/udp
    volumes:
    - ./data/influxdb-storage:/var/lib/influxdb:rw
    - ./config/influxdb.conf:/etc/influxdb/influxdb.conf
    # environment: 
    #   INFLUXDB_DB: auto-telemetry
    #   # INFLUXDB_ADMIN: admin_atc
    #   # INFLUXDB_ADMIN_PASSWORD: adminPassword123
    #   INFLUXDB_USER: atc
    #   INFLUXDB_USER_PASSWORD: atc
    #   INFLUXDB_HTTP_AUTH_ENABLED: "true"
    command: ["-config", "/etc/influxdb/influxdb.conf"]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes: 
    - ./data/grafana-storage:/var/lib/grafana:rw

  auto-telemetry-collector:
    image: inosion/auto-telemetry
    container_name: auto-telemetry-collector
    volumes:
      # - ./bluetooth-rfcomm.conf:/etc/bluetooth/rfcomm.conf:ro
      - ./auto-telemetry-collector.py:/usr/local/bin/auto-telemetry-collector.py:ro
    ports:
     - 5000:5000
    volumes:
      - ./:/host:ro
      - /dev:/dev:rw
      - /var:/var:rw
      - /sys:/sys:rw
    privileged: true
    working_dir: /host
    environment:
      - ATC_CONFIG=/etc/auto-telemetry-collector/default-auto-telemetry-config.yaml    
    command: ["monitor", "--device", "/dev/ttyUSB0" , "--config", "${ATC_CONFIG}"]
    depends_on:
      - grafana
