{
 "title": "OBD2 Monitor",
 "time": { "from": "2020-06-14T06:31:10.085Z", "to": "2020-06-14T07:05:58.808Z" },
 "templating": {
  "list": [
   { "name": "vehicle", "label": "Vehicle", "query": "stats.gauges.*" }
  ]
 },
 "panels": [
  {
   "title": "RPM and Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$vehicle.RPM_revolutions_per_minute, 3)"
    },
    {
     "target": "aliasByNode(stats.gauges.$vehicle.SPEED_kph, 3)"
    },
    {
     "target": "aliasByNode(stats.gauges.$vehicle.THROTTLE_POS_B_percent, 3)"
    }
   ]
  },
  {
   "title": "KPH",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(maxSeries(stats.gauges.$vehicle.SPEED_kph), 3)"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(maxSeries(stats.gauges.$vehicle.RPM_revolutions_per_minute), 3)"
    }
   ]
  },
  {
   "title": "Temp C",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(maxSeries(stats.gauges.$vehicle.COOLANT_TEMP_degC), 3)"
    }
   ]
  },
  {
   "title": "Coolant Temp",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$vehicle.COOLANT_TEMP_degC, 3)"
    }
   ]
  },
  {
   "title": "Short & Long Fuel Trims",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$vehicle.SHORT_FUEL_TRIM_1_percent, 3)"
    },
    {
     "target": "aliasByNode(stats.gauges.$vehicle.LONG_FUEL_TRIM_1_percent, 3)"
    }
   ]
  }
 ]
}