{
 "title": "OBD2 Monitor",
 "time": { "from": "2020-06-30T22:22:30.331Z", "to": "2020-06-30T22:43:34.674Z" },
 "templating": {
  "list": [
   { "name": "vehicle", "label": "Vehicle", "query": "stats.gauges.*" }
  ]
 },
 "panels": [
  {
   "title": "RPM and Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RPM",
     "select": [
      [
       { "params": [ "revolutions_per_minute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "aliasByNode(stats.gauges.$vehicle.RPM_revolutions_per_minute, 3)"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SPEED",
     "select": [
      [
       { "params": [ "kph" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "aliasByNode(stats.gauges.$vehicle.SPEED_kph, 3)"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "THROTTLE_POS_B",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "aliasByNode(stats.gauges.$vehicle.THROTTLE_POS_B_percent, 3)"
    }
   ]
  },
  {
   "title": "KPH",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SPEED",
     "select": [
      [
       { "params": [ "kph" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "aliasByNode(maxSeries(stats.gauges.$vehicle.SPEED_kph), 3)"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "content": "<table>\n<tr>\n  <td>\n  <button class=\"btn navbar-button gf-timepicker-nav-btn\" onClick=\"location.href='insert url here'\" >\t&#x2753;  Get DTC Codes</button></br>\n  </td>\n  <td>\n  <button class=\"btn navbar-button gf-timepicker-nav-btn\" onClick=\"location.href='insert url here'\" >\tShow Vehicle Info</button></br>\n  </td>\n</tr>\n<tr>\n  <td>\n  <button class=\"btn navbar-button gf-timepicker-nav-btn\" onClick=\"location.href='insert url here'\"> \t&#x2327;  Reset DTC Codes</button>\n  </td>\n</tr>\n</table>  \n\n<script>\n\nfunction getCodes() {\n  \n  $.get( \"http://localhost:5000/getcodes\" , function( data ) {\n    $( \"#output\" ).html( data );\n  });\n  \n}\n\n</script>\n<a href=\"#\" onclick=\"getCodes();\">Get Codes</a>\n<p id=\"output\"></p>"
  },
  {
   "title": "Temp C",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "COOLANT_TEMP",
     "select": [
      [
       { "params": [ "degC" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "aliasByNode(maxSeries(stats.gauges.$vehicle.COOLANT_TEMP_degC), 3)"
    }
   ]
  },
  {
   "title": "Coolant Temp",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "COOLANT_TEMP",
     "select": [
      [
       { "params": [ "degC" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "aliasByNode(stats.gauges.$vehicle.COOLANT_TEMP_degC, 3)"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RPM",
     "select": [
      [
       { "params": [ "revolutions_per_minute" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "aliasByNode(maxSeries(stats.gauges.$vehicle.RPM_revolutions_per_minute), 3)"
    }
   ]
  },
  {
   "title": "Short & Long Fuel Trim %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LONG_FUEL_TRIM_1",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$vehicle$/" }
     ],
     "target": "aliasByNode(stats.gauges.$vehicle.SHORT_FUEL_TRIM_1_percent, 3)"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SHORT_FUEL_TRIM_1",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "aliasByNode(stats.gauges.$vehicle.LONG_FUEL_TRIM_1_percent, 3)"
    }
   ]
  },
  {
   "title": "Intake Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "INTAKE_PRESSURE",
     "select": [
      [
       { "params": [ "kilopascal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "stats.gauges.$vehicle.INTAKE_PRESSURE_kilopascal"
    }
   ]
  },
  {
   "title": "Timing Advance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TIMING_ADVANCE",
     "select": [
      [
       { "params": [ "degree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "stats.gauges.$vehicle.TIMING_ADVANCE_degree"
    }
   ]
  },
  {
   "title": "O2 Sensor V and A",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "O2_B1S2",
     "select": [
      [
       { "params": [ "volt" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "aliasByNode(stats.gauges.$vehicle.O2_S1_WR_CURRENT_milliampere, 3)"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "O2_S1_WR_CURRENT",
     "select": [
      [
       { "params": [ "milliampere" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=", "value": "peugeot308" }
     ],
     "target": "aliasByNode(stats.gauges.$vehicle.O2_B1S2_volt, 3)"
    }
   ]
  }
 ]
}